package com.artusofabio.bankappvm;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Transaction {

    private Integer transactionId;  // in this case Id is hard coded and not autogenerated
    private LocalDate transactionDate;
    private String vendor;
    private String type;
    private double amount;
    private String category;


}
